// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdoyhBXVHBqHiJzWm8JfxiGY2MFcB_LsE',
    appId: '1:84444508251:web:4bb4f3c3c11e1b76d40f7e',
    messagingSenderId: '84444508251',
    projectId: 'utilityapp-c95e4',
    authDomain: 'utilityapp-c95e4.firebaseapp.com',
    storageBucket: 'utilityapp-c95e4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMWudSXLQnVwpm8WsAO495HsXjuEfKVlk',
    appId: '1:84444508251:android:4ebbbd72b36bb2c0d40f7e',
    messagingSenderId: '84444508251',
    projectId: 'utilityapp-c95e4',
    storageBucket: 'utilityapp-c95e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxAPLyqfCKKwG7a2qzHNb6KV9hMp3mkNo',
    appId: '1:84444508251:ios:14fcb879ab929318d40f7e',
    messagingSenderId: '84444508251',
    projectId: 'utilityapp-c95e4',
    storageBucket: 'utilityapp-c95e4.firebasestorage.app',
    iosBundleId: 'com.example.utilityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxAPLyqfCKKwG7a2qzHNb6KV9hMp3mkNo',
    appId: '1:84444508251:ios:14fcb879ab929318d40f7e',
    messagingSenderId: '84444508251',
    projectId: 'utilityapp-c95e4',
    storageBucket: 'utilityapp-c95e4.firebasestorage.app',
    iosBundleId: 'com.example.utilityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdoyhBXVHBqHiJzWm8JfxiGY2MFcB_LsE',
    appId: '1:84444508251:web:7083ee030c408658d40f7e',
    messagingSenderId: '84444508251',
    projectId: 'utilityapp-c95e4',
    authDomain: 'utilityapp-c95e4.firebaseapp.com',
    storageBucket: 'utilityapp-c95e4.firebasestorage.app',
  );
}
